on: push
jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm install-ci-test
      - run: npm run build && npm publish
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
